# Generated by Django 3.1.12 on 2022-01-29 07:19

from django.db import migrations, models
import django.db.models.deletion
import djongo.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comp_name', models.CharField(max_length=300)),
                ('numero_compagnie', models.CharField(max_length=15)),
                ('data', djongo.models.fields.JSONField(default={'key': 'value'})),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=500)),
                ('username', models.CharField(blank=True, max_length=30)),
                ('number', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(max_length=200)),
                ('register_on', models.DateTimeField(auto_now=True)),
                ('is_client', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_moniteur', models.BooleanField(default=False)),
                ('isAgentLivraison', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_super', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('prenom_client', models.CharField(max_length=180)),
                ('num_tel_client', models.CharField(max_length=15)),
                ('localisation', models.CharField(max_length=200)),
                ('departure_city', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('travelDate', models.DateField()),
                ('travelCost', models.IntegerField()),
                ('h_commande', models.DateTimeField(auto_now=True)),
                ('receipt_commande_time_from_customer', models.TimeField(blank=True)),
                ('time_to_send_commande_to_monitor', models.TimeField(blank=True)),
                ('time_confirmation_commande_from_monitor', models.TimeField(blank=True)),
                ('feedback_commande_time_from_monitor', models.TimeField(blank=True)),
                ('receipt_commande_time_from_monitor', models.TimeField(blank=True)),
                ('time_to_send_commande_to_delivery_guy', models.TimeField(blank=True)),
                ('compagnie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Voyage.compagnie')),
            ],
        ),
    ]
