# Generated by Django 3.1.12 on 2022-02-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Voyage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='siege_compagnie',
            field=models.CharField(default='ABOBO', max_length=100),
        ),
        migrations.AddField(
            model_name='myuser',
            name='habitation',
            field=models.CharField(default='COCODY', max_length=200),
        ),
    ]
